export const resume = {
  avatar: {
    public_id: "resumeCraft_resume_Avatar/r1ghwsvv0jezkyleo1zv",
    url: "https://res.cloudinary.com/dvbgu8nqo/image/upload/v1707754213/resumeCraft_resume_Avatar/jaxaasieblvqlsnyfqa4.png",
  },
  _id: "5eAbht53U8KrAZtvNuJJv",
  educations: [
    {
      _id: 1,
      school: "BG",
      degree: "SSC",
      startMontYear: "Feb,2024",
      endMontYear: "Feb,2024",
      city: "Rangpur",
      description:
        " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil maxime unde rerum dolore totam quasi impedit, reprehenderit voluptatum dolores laudantium similique consequuntur quod, delectus omnis voluptatem nulla nostrum. Ratione, veniam.",
    },
    {
      _id: 2,
      school: "DD",
      degree: "MD",
      startMontYear: "Feb,2024",
      endMontYear: "Feb,2024",
      city: "DB",
      description:
        " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil maxime unde rerum dolore totam quasi impedit, reprehenderit voluptatum dolores laudantium similique consequuntur quod, delectus omnis voluptatem nulla nostrum. Ratione, veniam.",
    },
  ],
  historyId: "Ekkw4OA6xKV_fGyysr1us",
  languages: [
    {
      _id: 1,
      language: "Bangla",
      level: "1",
    },
    {
      _id: 2,
      language: "English",
      level: "1",
    },
  ],
  personalInfo: {
    _id: "",
    jobTitle: "Frontend Dev",
    firstName: "Satya Ranjon",
    lastName: "Sharma",
    email: "demo@gmail.com",
    phoneNumber: "01984553087",
    country: "Bangladesh",
    city: "Rangpur",
    address: "Lalgbag",
    postalCode: "5200",
    drivingLicense: "0142584712121",
    nationality: "Bangladesi",
    placeOfBirth: "Bangladesh",
    DateOfBirth: "Rangpur",
  },
  professionalSummary:
    " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil maxime unde rerum dolore totam quasi impedit, reprehenderit voluptatum dolores laudantium similique consequuntur quod, delectus omnis voluptatem nulla nostrum. Ratione, veniam.",
  references: [
    {
      _id: 1,
      name: "Example",
      company: "Example",
      phone: "",
      email: "Example",
    },
  ],
  sectionTitles: {
    _id: "",
    personalInfo: "Personal Details",
    professionalSummary: "Professional Summary",
    workExperience: "Employment",
    skills: "Skills",
    languages: "Languages",
    references: "References",
    educations: "Education",
    socialProfiles: "Websites & Social",
  },
  fontSize: {
    height: "1190.14px",
    width: "852px",
  },
  skills: [
    {
      _id: 1,
      label: "Html",
      level: 20,
    },
    {
      _id: 2,
      label: "Javascript",
      level: 60,
    },
  ],
  socialProfiles: [
    {
      _id: 1,
      label: "Facebook",
      link: "facebook.com",
    },
    {
      _id: 2,
      label: "Youtube",
      link: "youtube.com",
    },
  ],
  style: {
    theme: "#0D9488",
    themeOptions: ["#084C41", "#65A30D", "#0D9488"],
    skillLevel: true,
    skillLevelDisabled: true,
    personalInfo: {
      jobTitle: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWidth: 600,
        fontSize: "22px",
        textAlign: "center",
      },
      firstName: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWidth: 600,
        fontSize: "22px",
        textAlign: "center",
      },
      lastName: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWidth: 600,
        fontSize: "22px",
        textAlign: "end",
      },
      email: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWidth: 600,
        fontSize: "22px",
        textAlign: "start",
      },
      phoneNumber: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWidth: 600,
        fontSize: "22px",
        textAlign: "start",
      },
      country: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWidth: 600,
        fontSize: "22px",
        textAlign: "start",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWidth: 200,
        fontSize: "",
        textAlign: "",
      },
      address: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      postalCode: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      drivingLicense: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      nationality: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      placeOfBirth: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      DateOfBirth: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    workExperience: {
      city: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      employer: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      endMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    skills: {
      label: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "#0D9488",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "44px",
        textAlign: "center",
      },
    },
    languages: {
      language: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    references: {
      name: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      company: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      phone: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    educations: {
      school: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      degree: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      endMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    socialProfiles: {
      label: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      link: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      professionalSummaryStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      workExperienceStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      skillsStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      languagesStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      referencesStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      educationsStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
      socialProfilesStyle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        fontSize: "",
        textAlign: "",
      },
    },
  },
  templateId: "stockholm01",
  workExperience: [
    {
      _id: 1,
      city: "Bangladash Dhaka",
      description:
        " Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nihil maxime unde rerum dolore totam quasi impedit, reprehenderit voluptatum dolores laudantium similique consequuntur quod, delectus omnis voluptatem nulla nostrum. Ratione, veniam.",
      employer: "LB limited",
      endMontYear: "Feb,2023",
      jobTitle: "Frontend Dev",
      startMontYear: "Feb,2022",
    },
  ],
  zoom: 0.7,
};
