export const resume = {
  avatar: {
    public_id: "resumeCraft_resume_Avatar/fzzm5nmnt3ysvsabutjf",
    url: "https://res.cloudinary.com/dvbgu8nqo/image/upload/v1708373962/resumeCraft_resume_Avatar/fzzm5nmnt3ysvsabutjf.png",
  },
  _id: "KQ_2iUYqmYYZD3l1bH8Bo",
  educations: [
    {
      _id: "wywcY1ZFRV46bFydcFApK",
      school: "Dinajpur Zilla School",
      degree: "SSC",
      startMontYear: "Feb,2014",
      endMontYear: "Feb,2020",
      city: "Dinajpur",
      description:
        "Educated at Dinajpur Zilla School, where I developed a strong academic foundation and demonstrated leadership skills. ",
    },
    
  ],
  historyId: "9YYaiND53dftoljQe4lqn",
  languages: [
    {
      _id: "sJHoORxv4pkJTbWDnW0eN",
      language: "English",
      level: "Basic",
    },
    {
      _id: "-SnlMEy3XGZm20vRyi0HS",
      language: "Bangla",
      level: "Native",
    },
  ],
  personalInfo: {
    _id: "",
    jobTitle: "Frontend Devloper",
    firstName: "Shatya Ranjon ",
    lastName: "Sharma",
    email: "khokondemo@gmail.com",
    phoneNumber: "01700000000",
    country: "Bangladesh",
    city: "Rangpur",
    address: "Lalbag",
    postalCode: "5200",
    drivingLicense: "01.0215.021",
    nationality: "Bangladeshi",
    placeOfBirth: "Rangpur",
    DateOfBirth: "10-10-2004",
  },
  professionalSummary:
    "Experienced Frontend Web Developer with a passion for crafting user-friendly interfaces. Proficient in HTML, CSS, and JavaScript, with expertise in responsive design and frameworks like React. Dedicated to delivering high-quality code and collaborating effectively in fast-paced environments",
  references: [
    {
      _id: "Dm-8YXb6joyaRdRyRwpFI",
      name: "khokon Sharma",
      company: "LD limited",
      phone: "01700000000",
      email: "khokondemo@gmail.com",
    },
    {
      _id: "h5wOYGWsSfkpof7OMphi7",
      name: "Shatya Ranjon Sharma",
      company: "SD limited",
      phone: "01700000000",
      email: "khokondemo@gmail.com",
    },
  ],
  sectionTitles: {
    _id: "",
    personalInfo: "Personal",
    professionalSummary: "Professional Summary",
    workExperience: "Employment",
    skills: "Skills",
    languages: "Language",
    references: "References",
    educations: "Education",
    socialProfiles: "Social",
  },
  size: {
    height: "792px",
    width: "612px",
  },
  skills: [
    {
      _id: "jqNWWw8uTQsyygeOCvHrB",
      label: "Html",
      level: 80,
    },
    {
      _id: "CLJ1uSQjmDv66-sZ-yiKK",
      label: "Javascript",
      level: 80,
    },
    {
      _id: "GDLwI-C5eVriRB7MVXW5f",
      label: "AWS",
      level: 60,
    },
    {
      _id: "NNLm27A3HiQ_9lcqybE5U",
      label: "Typescript",
      level: 60,
    },
    {
      _id: "IKARGF-iDuN2MqR2Qacoa",
      label: "CSS",
      level: 60,
    },
    {
      _id: "mBfovGyUscfh7Jz4TToMU",
      label: "ReactJS",
      level: 80,
    },
    {
      _id: "YyiGXMnvhNFQkA6rFjt0Y",
      label: "NextJs",
      level: 40,
    },
  ],
  socialProfiles: [
    {
      _id: "rAQG-bPHrkV9rvBBVpB1n",
      label: "Youtube",
      link: "https://www.youtube.com/watch?v=7USf9qWTqmE",
    },
    {
      _id: "PdOcN3DPUjXhK-BVj4DU1",
      label: "Facebook",
      link: "https://www.youtube.com/watch?v=7USf9qWTqmE",
    },
  ],
  style: {
    theme: "#FFF66D",
    themeOptions: ["#E4E4E4", "#FED78C", "#9AEBFE", "#FFF66D", "#4BFBBA"],
    skillLevel: false,
    skillLevelDisabled: false,
    personalInfo: {
      jobTitle: {
        color: "#172554",
        fontFamily: "Nunito",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      firstName: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 700,
        fontSize: "20px",
        textAlign: "start",
      },
      lastName: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 700,
        fontSize: "20px",
        textAlign: "start",
      },
      email: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "14px",
        textAlign: "start",
      },
      phoneNumber: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      country: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      city: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      address: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      postalCode: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      drivingLicense: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      nationality: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      placeOfBirth: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      DateOfBirth: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    workExperience: {
      city: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      description: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      employer: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      endMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      jobTitle: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      startMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    skills: {
      label: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    languages: {
      language: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "12px",
        textAlign: "start",
      },
      level: {
        color: "#6d696d",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "10px",
        textAlign: "start",
      },
    },
    references: {
      name: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      company: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      phone: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      email: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    educations: {
      school: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      degree: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      startMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      endMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      city: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      description: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    socialProfiles: {
      label: {
        color: "#6EA3F8",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      link: {
        color: "#6EA3F8",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      professionalSummaryStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      workExperienceStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      skillsStyle: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      languagesStyle: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      referencesStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      educationsStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      socialProfilesStyle: {
        color: "#FFFFFF",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
    },
  },
  templateId: "vienna01",
  workExperience: [
    {
      _id: "eeYQn3dNzL-ApfDlLMo9L",
      city: "Dhaka",
      description:
        "\nExperienced Frontend Web Developer with a passion for crafting user-friendly interfaces. Proficient in HTML, CSS, and JavaScript, with expertise in responsive design and frameworks like React. Dedicated to delivering high-quality code and collaborating effectively in fast-paced environments.",
      employer: "BD limited",
      endMontYear: "Feb,2021",
      jobTitle: "Frontend Dev",
      startMontYear: "Feb,2020",
    },
    {
      _id: "5o-BXHCdd1xNKGCYvZ2in",
      city: "Dhaka",
      description:
        "\nSeasoned Backend Web Developer adept in building scalable, efficient, and secure web applications. Skilled in backend technologies such as Node.js, Python, and SQL databases. ",
      employer: "LD limited",
      endMontYear: "Feb,2023",
      jobTitle: "Backend Dev",
      startMontYear: "Feb,2022",
    },
  ],
  zoom: 1,
};
