export const resume = {
  avatar: {
    public_id: "resumeCraft_resume_Avatar/x6kskr19dd8tvilmkm4i",
    url: "https://res.cloudinary.com/dvbgu8nqo/image/upload/v1708093264/resumeCraft_resume_Avatar/x6kskr19dd8tvilmkm4i.webp",
  },
  _id: "g7d6YRswdE_kDsmGqa2fQ",
  educations: [
    {
      _id: 1,
      school: "Dinajpur Zilla School",
      degree: "SSC",
      startMontYear: "Feb,2015",
      endMontYear: "Feb,2020",
      city: "Dinajpur",
      description:
        "Educated at Dinajpur Zilla School, where I developed a strong academic foundation and demonstrated leadership skills. Graduated with honors, showcasing dedication to learning and excellence.",
    },
  ],
  historyId: "PcvC3QEd4JAOyC4muBPlI",
  languages: [
    {
      _id: 1,
      language: "English",
      level: "Basic",
    },
    {
      _id: 2,
      language: "Bangla",
      level: "Native",
    },
  ],
  personalInfo: {
    _id: "",
    jobTitle: "Frontend Developer",
    firstName: "Satya Ranjon",
    lastName: "Sharma",
    email: "satyaranjonofficial@gmail.com",
    phoneNumber: "01746958640",
    country: "Bangladesh",
    city: "Rangpur",
    address: "Lalbag",
    postalCode: "5200",
    drivingLicense: "01.2541021.0",
    nationality: "Bangladeshi",
    placeOfBirth: "Rangpur",
    DateOfBirth: "10-10-2004",
  },
  professionalSummary:
    "Dynamic and results-oriented professional with over five years of experience in marketing and project management within the technology sector. ",
  references: [
    {
      _id: 1,
      name: "Khokon Sharma",
      company: "GMT limited",
      phone: "01725100001",
      email: "khokon@gmail.com",
    },
  ],
  sectionTitles: {
    _id: "",
    personalInfo: "Personal Data",
    professionalSummary: "Professional Summary",
    workExperience: "Employment",
    skills: "Skills",
    languages: "Languages",
    references: "References",
    educations: "Education",
    socialProfiles: "Social",
  },
  size: {
    height: "1190.14px",
    width: "852px",
  },
  skills: [
    {
      _id: 1,
      label: "Html",
      level: 80,
    },
    {
      _id: 2,
      label: "Javascript",
      level: 60,
    },
    {
      _id: 3,
      label: "CSS",
      level: 60,
    },
    {
      _id: 4,
      label: "Typescript",
      level: 40,
    },
    {
      _id: 5,
      label: "Nodejs",
      level: 60,
    },
    {
      _id: 6,
      label: "MongoDB",
      level: 60,
    },
    {
      _id: 7,
      label: "Mongoose",
      level: 80,
    },
  ],
  socialProfiles: [
    {
      _id: 1,
      label: "Github",
      link: "https://github.com/satya-ranjon",
    },
    {
      _id: 2,
      label: "Facebook",
      link: "https://www.facebook.com/satyaranjonsharma/",
    },
  ],
  style: {
    theme: "#4AFBB9",
    themeOptions: [],
    skillLevel: true,
    skillLevelDisabled: true,
    personalInfo: {
      jobTitle: {
        color: "#000000",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 800,
        fontSize: "25px",
        textAlign: "start",
      },
      firstName: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "35px",
        textAlign: "start",
      },
      lastName: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "35px",
        textAlign: "start",
      },
      email: {
        color: "#387BE8",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "18px",
        textAlign: "start",
      },
      phoneNumber: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "18px",
        textAlign: "start",
      },
      country: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "18px",
        textAlign: "start",
      },
      city: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "18px",
        textAlign: "start",
      },
      address: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "18px",
        textAlign: "start",
      },
      postalCode: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "18px",
        textAlign: "start",
      },
      drivingLicense: {
        color: "#545556",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      nationality: {
        color: "#545556",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      placeOfBirth: {
        color: "#545556",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      DateOfBirth: {
        color: "#545556",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    workExperience: {
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 200,
        fontSize: "",
        textAlign: "",
      },
      employer: {
        color: "",
        fontFamily: "",
        fontWeight: 600,
        fontSize: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    skills: {
      label: {
        color: "",
        fontFamily: "18px",
        fontWeight: 600,
        fontSize: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "",
        fontFamily: "",
        fontWeight: 200,
        fontSize: "",
        textAlign: "start",
      },
    },
    languages: {
      language: {
        color: "",
        fontFamily: "18px",
        fontWeight: 600,
        fontSize: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    references: {
      name: {
        color: "",
        fontFamily: "",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "",
      },
      company: {
        color: "",
        fontFamily: "",
        fontWeight: 600,
        fontSize: "",
        textAlign: "",
      },
      phone: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      email: {
        color: "#ffffff",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    educations: {
      school: {
        color: "",
        fontFamily: "",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "",
      },
      degree: {
        color: "",
        fontFamily: "",
        fontWeight: 600,
        fontSize: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    socialProfiles: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      link: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
      professionalSummaryStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
      workExperienceStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
      skillsStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
      languagesStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
      referencesStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
      educationsStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
      socialProfilesStyle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        fontSize: "20px",
        textAlign: "start",
      },
    },
  },
  templateId: "sydney01",
  workExperience: [
    {
      _id: 1,
      city: "Dhaka,Bangladesh",
      description:
        "Experienced frontend developer proficient in HTML, CSS, and JavaScript, with expertise in React, Vue.js, and Angular. Skilled in Git for version control. Strong eye for design, focusing on user-friendly interfaces. Dedicated to translating design concepts into clean, maintainable code while ensuring cross-browser compatibility and optimal performance. ",
      employer: "HB limited",
      endMontYear: "Aug,2021",
      jobTitle: "Frontend Developer",
      startMontYear: "Feb,2020",
    },
    {
      _id: 2,
      city: "Dhaka,Bangladesh",
      description:
        "Experienced backend developer proficient in languages such as Python, Java, and Node.js, with expertise in frameworks like Django and Spring Boot. Skilled in database management using SQL and NoSQL technologies. Strong understanding of RESTful API design and development..",
      employer: "RMD limited",
      endMontYear: "Nov,2023",
      jobTitle: "Backend Developer",
      startMontYear: "Feb,2022",
    },
  ],
  zoom: 0.7,
};
