const styleToronto = {
  require: {
    theme: "#232323",
    themeOptions: ["#232323", "#172F53", "#361146", "#160A45", "#324739"],
    skillLevel: true,
    skillLevelDisabled: true,
    personalInfo: {
      jobTitle: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        size: "22px",
        textAlign: "center",
      },
      firstName: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        size: "22px",
        textAlign: "center",
      },
      lastName: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        size: "22px",
        textAlign: "end",
      },
      email: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        size: "22px",
        textAlign: "start",
      },
      phoneNumber: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        size: "22px",
        textAlign: "start",
      },
      country: {
        color: "#fcfcfc",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        size: "22px",
        textAlign: "start",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      address: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      postalCode: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      drivingLicense: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      nationality: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      placeOfBirth: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      DateOfBirth: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    workExperience: {
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      employer: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      endMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    skills: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "#0D9488",
        fontFamily: "",
        fontWeight: 0,
        size: "44px",
        textAlign: "center",
      },
    },
    languages: {
      language: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    references: {
      name: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      company: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      phone: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    educations: {
      school: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      degree: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      endMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    socialProfiles: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      link: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      professionalSummaryStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      workExperienceStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      skillsStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      languagesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      referencesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      educationsStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      socialProfilesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
  },
};

export default styleToronto;
