const styleToronto = {
  require: {
    theme: "#232323",
    themeOptions: ["#232323", "#172F53", "#361146", "#160A45", "#324739"],
    personalInfo: {
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      firstName: {
        color: "#00000",
        fontFamily: "'Lato', sans-serif",
        fontWidth: 600,
        size: "22px",
        textAlign: "center",
      },
      lastName: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      phoneNumber: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      country: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      address: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      postalCode: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      drivingLicense: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      nationality: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      placeOfBirth: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      DateOfBirth: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
    workExperience: {
      city: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      employer: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      endMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
    skills: {
      label: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
    languages: {
      language: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
    references: {
      name: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      company: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      phone: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
    educations: {
      school: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      degree: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      endMontYear: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
    socialProfiles: {
      label: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      link: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
    sectionTitles: {
      personalInfo: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      professionalSummary: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      workExperience: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      skills: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      languages: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      references: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      educations: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
      socialProfiles: {
        color: "",
        fontFamily: "",
        fontWidth: 0,
        size: "",
        textAlign: "",
      },
    },
  },
};

export default styleToronto;
