// https://i.ibb.co/zJdVXq1/madrid-resume-templates.webp

const styleMadrid = {
  common: {
    container: {
      padding: "48px",
      width: "100%",
      height: "100%",
    },
    header: {
      display: "flex",
      gap: "10px",
    },

    headerDivOne: {
      width: "400px",
      minHeight: "200px",
      maxHeight: "250px",
      
      borderRight: "10px solid #ffffff",

    },
    headerDivTwo: {
      padding: "30px",
      width: "100%",
    },
    body: {
      // display: "flex",
      // gap: "20px",
      // padding: "40px 40px 40px 40px",
      paddingTop:"40px",
    },
    // bodyDivOne: {
    //   width: "300px",
    //   border: "10px solid red",
    // },
    // bodyDivTwo: {
    //   padding: "30px",
    //   width: "100%",
    // },
    personalInfoLabel: {
      color: "#002B18",
      fontFamily: "'Lato', sans-serif",
      fontWeight: 700,
      size: "35px",
    },
  },
  require: { 
    theme: "#FFE14C",
    themeOptions: ["#FFE14C", "#FF9737", "#91D8E2", "#F6AFAD", "#6295EC"],
    skillLevel: true,
    skillLevelDisabled: true,
    personalInfo: {
      jobTitle: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 600,
        size: "20px",
        textAlign: "start",
      },
      firstName: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 800,
        size: "40px",
        textAlign: "start",
      },
      lastName: {
        color: "#002B18",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 800,
        size: "40px",
        textAlign: "start",
      },
      email: {
        color: "#387BE8",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "18px",
        textAlign: "start",
      },
      phoneNumber: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
      country: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
      city: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
      address: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
      postalCode: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
      drivingLicense: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
      nationality: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
        // border: "1px solid red",
      },
      placeOfBirth: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
      DateOfBirth: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
      },
    },
    workExperience: {
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      employer: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    skills: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "black",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 400,
        size: "20px",
        textAlign: "start",
        marginBottom: "5px",
        marginTop: "5px",
      },
    },
    languages: {
      language: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    references: {
      name: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      company: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      phone: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    educations: {
      school: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      degree: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    socialProfiles: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      link: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "#ffffff",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 300,
        size: "20px",
        textAlign: "start",
        backgroundColor: "black",
        padding: "5px 5px 5px 5px",
        // maxWidth: "50%",
        display: "inline-block",
        // border: "1px solid #ffffff",
        textTransform: "uppercase",
        marginBottom: "5px",
        
      },
      professionalSummaryStyle: {
        color: "#ffffff",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 300,
        size: "20px",
        textAlign: "start",
        backgroundColor: "black",
        padding: "5px 5px 5px 5px",
        // maxWidth: "50%",
        display: "inline-block",
        // border: "1px solid #ffffff",
        textTransform: "uppercase",
        marginBottom: "5px",
        marginTop: "5px",
      },
      workExperienceStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
        marginBottom: "5px",
      },
      skillsStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      languagesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      referencesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      educationsStyle: {
        color: "#ffffff",
        fontFamily: "'Lato', sans-serif",
        fontWeight: 300,
        size: "20px",
        textAlign: "start",
        backgroundColor: "black",
        padding: "5px 5px 5px 5px",
        // maxWidth: "50%",
        display: "inline-block",
        // border: "1px solid #ffffff",
        textTransform: "uppercase",
        marginBottom: "5px",
        marginTop: "5px",
      },
      socialProfilesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
  },
};

export default styleMadrid;
