const styleVienna = {
  common: {
    container: {
      padding: "48px 48px",
      width: "100%",
      height: "100%",
    },
    header: {
      display: "flex",
      gap: "35px",
    },

    headerDivOne: {
      minWidth: "200px",
      minHeight: "200px",
      maxHeight: "250px",
    },
    headerDivTwo: {
      padding: "20px 0px",
      width: "100%",
    },

    personalInfoEmail: {
      marginLeft: "10px",
    },

    body: {
      display: "flex",
      gap: "35px",
      padding: "40px 0px 0px 0px",
    },
    bodyDivOne: {
      width: "200px",
    },
    bodyDivTwo: {
      width: "100%",
    },
    personalInfoLabel: {
      color: "#002B18",
      fontFamily: "Roboto",
      fontWeight: 600,
      fontSize: "15px",
    },

    skillsLevelContainer: {
      width: "200px",
      backgroundColor: "#d1d1d1",
      height: "4px",
      display: "flex",
      gap: "4px",
    },

    skillsLevel: { width: `20%`, backgroundColor: "#3a3139", height: "100%" },
  },
  require: {
    theme: "#4BFBBA",
    themeOptions: ["#E4E4E4", "#FED78C", "#9AEBFE", "#FFF66D", "#4BFBBA"],
    skillLevel: false,
    skillLevelDisabled: false,
    personalInfo: {
      jobTitle: {
        color: "#172554",
        fontFamily: "Nunito",
        fontWeight: 600,
        fontSize: "25px",
        textAlign: "start",
      },
      firstName: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 700,
        fontSize: "42px",
        textAlign: "start",
      },
      lastName: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 700,
        fontSize: "42px",
        textAlign: "start",
      },
      email: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "16px",
        textAlign: "start",
      },
      phoneNumber: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "16px",
        textAlign: "start",
      },
      country: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "16px",
        textAlign: "start",
      },
      city: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "16px",
        textAlign: "start",
      },
      address: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "16px",
        textAlign: "start",
      },
      postalCode: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "16px",
        textAlign: "start",
      },
      drivingLicense: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      nationality: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      placeOfBirth: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      DateOfBirth: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    workExperience: {
      city: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      description: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      employer: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      endMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "17px",
        textAlign: "start",
      },
      jobTitle: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      startMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "17px",
        textAlign: "start",
      },
    },
    skills: {
      label: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    languages: {
      language: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "15px",
        textAlign: "start",
      },
      level: {
        color: "#6d696d",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    references: {
      name: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      company: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      phone: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      email: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    educations: {
      school: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      degree: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      startMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "17px",
        textAlign: "start",
      },
      endMontYear: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "17px",
        textAlign: "start",
      },
      city: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      description: {
        color: "#172554",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    socialProfiles: {
      label: {
        color: "#6EA3F8",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      link: {
        color: "#6EA3F8",
        fontFamily: "Roboto",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
      professionalSummaryStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
      workExperienceStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
      skillsStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
      languagesStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
      referencesStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
      educationsStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
      socialProfilesStyle: {
        color: "#002B18",
        fontFamily: "Roboto",
        fontWeight: 600,
        fontSize: "24px",
        textAlign: "start",
      },
    },
  },
};

export default styleVienna;
