// https://i.ibb.co/vhVpMbg/brussels-resume-templates.webp

const styleBrussels = {
  require: {
    theme: "#3C78D8",
    themeOptions: ["#3C78D8", "#C799A6", "#90909E", "#909580"],
    skillLevel: true,
    skillLevelDisabled: true,
    personalInfo: {
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      firstName: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      lastName: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "start",
      },
      phoneNumber: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "start",
      },
      country: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "start",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      address: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      postalCode: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      drivingLicense: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      nationality: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      placeOfBirth: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      DateOfBirth: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    workExperience: {
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      employer: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    skills: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    languages: {
      language: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    references: {
      name: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      company: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      phone: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    educations: {
      school: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      degree: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    socialProfiles: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      link: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      professionalSummaryStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      workExperienceStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      skillsStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      languagesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      referencesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      educationsStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
      socialProfilesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
  },
};

export default styleBrussels;
