// https://i.ibb.co/VSvZBY6/athens-resume-templates.webp

const styleAthens = {
  common: {
    container: {
      padding: "0px 0px",
      width: "100%",
      height: "100%",
      display: "flex",
    },
  },
  require: {
    theme: "#082A4D",
    themeOptions: ["#082A4D", "#581010", "#1D473A", "#32084D", "#1B212F"],
    skillLevel: false,
    skillLevelDisabled: false,
    personalInfo: {
      jobTitle: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      firstName: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 700,
        fontSize: "24px",
        textAlign: "start",
      },
      lastName: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 700,
        fontSize: "24px",
        textAlign: "start",
      },
      email: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      phoneNumber: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      country: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      city: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      address: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      postalCode: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      drivingLicense: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      nationality: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      placeOfBirth: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      DateOfBirth: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    workExperience: {
      city: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      description: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      employer: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      endMontYear: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      jobTitle: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      startMontYear: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    skills: {
      label: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        fontSize: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    languages: {
      language: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "12px",
        textAlign: "start",
      },
      level: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "10px",
        textAlign: "start",
      },
    },
    references: {
      name: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      company: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      phone: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
      email: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    educations: {
      school: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      degree: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "17px",
        textAlign: "start",
      },
      startMontYear: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      endMontYear: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      city: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "14px",
        textAlign: "start",
      },
      description: {
        color: "#172554",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
    },
    socialProfiles: {
      label: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "start",
      },
      link: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 400,
        fontSize: "15px",
        textAlign: "start",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      professionalSummaryStyle: {
        color: "#002B18",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      workExperienceStyle: {
        color: "#002B18",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      skillsStyle: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      languagesStyle: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      referencesStyle: {
        color: "#002B18",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      educationsStyle: {
        color: "#002B18",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
      socialProfilesStyle: {
        color: "#FFFFFF",
        fontFamily: "Nunito Sans",
        fontWeight: 600,
        fontSize: "18px",
        textAlign: "start",
      },
    },
  },
};

export default styleAthens;
