// https://i.ibb.co/TKPqbjH/stockholm-resume-templates.webp

const styleSydney = {
  require: {
    theme: "#2196F3",
    themeOptions: ["#0F141F", "#673AB7", "#2196F3", "#22A860", "#FF4D4D"],
    skillLevel: true,
    skillLevelDisabled: true,
    personalInfo: {
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      firstName: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      lastName: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "start",
      },
      phoneNumber: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "start",
      },
      country: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "start",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      address: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      postalCode: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      drivingLicense: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      nationality: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      placeOfBirth: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      DateOfBirth: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    workExperience: {
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      employer: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      jobTitle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    skills: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    professionalSummary: {
      summery: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    languages: {
      language: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      level: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    references: {
      name: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      company: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      phone: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      email: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    educations: {
      school: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      degree: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      startMontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      MontYear: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      city: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      description: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    socialProfiles: {
      label: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      link: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
    sectionTitles: {
      personalInfoStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      professionalSummaryStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      workExperienceStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      skillsStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      languagesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      referencesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      educationsStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
      socialProfilesStyle: {
        color: "",
        fontFamily: "",
        fontWeight: 0,
        size: "",
        textAlign: "",
      },
    },
  },
};

export default styleSydney;
